version: '3.8'

services:
  frontend:
   
    build:
      context: ./react-car-care  
      dockerfile: Dockerfile
    
    ports:
      - "3000:3000"  
   
    environment:
      - REACT_APP_API_URL=http://localhost:5000  
  
    command: ["npm", "start"]
    
    volumes:
      - ./react-car-care:/app
      - /app/node_modules
